export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_RESET = "LOGIN_USER_RESET";

export const SIGNUP_USER_REQUEST = "SIGNUP_USER_REQUEST";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAILURE = "SIGNUP_USER_FAILURE";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const COMPANY_CATEGORY_REQUEST = "COMPANY_CATEGORY_REQUEST";
export const COMPANY_CATEGORY_SUCCESS = "COMPANY_CATEGORY_SUCCESS";
export const COMPANY_CATEGORY_FAILURE = "COMPANY_CATEGORY_FAILURE";

export const STATE_LIST_REQUEST = "STATE_LIST_REQUEST";
export const STATE_LIST_SUCCESS = "STATE_LIST_SUCCESS";
export const STATE_LIST_FAILURE = "STATE_LIST_FAILURE";

export const DISTRICT_LIST_REQUEST = "DISTRICT_LIST_REQUEST";
export const DISTRICT_LIST_SUCCESS = "DISTRICT_LIST_SUCCESS";
export const DISTRICT_LIST_FAILURE = "DISTRICT_LIST_FAILURE";

export const MUNICIPALITY_LIST_REQUEST = "MUNICIPALITY_LIST_REQUEST";
export const MUNICIPALITY_LIST_SUCCESS = "MUNICIPALITY_LIST_SUCCESS";
export const MUNICIPALITY_LIST_FAILURE = "MUNICIPALITY_LIST_FAILURE";

export const SIGNUP_LAB_REQUEST = "SIGNUP_LAB_REQUEST";
export const SIGNUP_LAB_SUCCESS = "SIGNUP_LAB_SUCCESS";
export const SIGNUP_LAB_FAILURE = "SIGNUP_LAB_FAILURE";
export const SIGNUP_LAB_RESET = "SIGNUP_LAB_RESET";

export const CHECK_UIDTOKEN_REQUEST = "CHECK_UIDTOKEN_REQUEST";
export const CHECK_UIDTOKEN_SUCCESS = "CHECK_UIDTOKEN_SUCCESS";
export const CHECK_UIDTOKEN_FAILURE = "CHECK_UIDTOKEN_FAILURE";

export const NEW_PASS_REQUEST = "NEW_PASS_REQUEST";
export const NEW_PASS_SUCCESS = "NEW_PASS_SUCCESS";
export const NEW_PASS_FAILURE = "NEW_PASS_FAILURE";
export const NEW_PASS_RESET = "NEW_PASS_RESET";
