export const GET_PACKAGES_REQUEST = "GET_PACKAGES_REQUEST";
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCCESS";
export const GET_PACKAGES_FAILURE = "GET_PACKAGES_FAILURE";

export const POST_PACKAGES_REQUEST = "POST_PACKAGES_REQUEST";
export const POST_PACKAGES_SUCCESS = "POST_PACKAGES_SUCCESS";
export const POST_PACKAGES_FAILURE = "POST_PACKAGES_FAILURE";
export const POST_PACKAGES_RESET = "POST_PACKAGES_RESET";

export const EDIT_PACKAGES_REQUEST = "EDIT_PACKAGES_REQUEST";
export const EDIT_PACKAGES_SUCCESS = "EDIT_PACKAGES_SUCCESS";
export const EDIT_PACKAGES_FAILURE = "EDIT_PACKAGES_FAILURE";
export const EDIT_PACKAGES_RESET = "EDIT_PACKAGES_RESET";

export const DELETE_PACKAGES_REQUEST = "DELETE_PACKAGES_REQUEST";
export const DELETE_PACKAGES_SUCCESS = "DELETE_PACKAGES_SUCCESS";
export const DELETE_PACKAGES_FAILURE = "DELETE_PACKAGES_FAILURE";
export const DELETE_PACKAGES_RESET = "DELETE_PACKAGES_RESET";

export const GET_LABTEST_REQUEST = "GET_LABTEST_REQUEST";
export const GET_LABTEST_SUCCESS = "GET_LABTEST_SUCCESS";
export const GET_LABTEST_FAILURE = "GET_LABTEST_FAILURE";

export const POST_LABTEST_REQUEST = "POST_LABTEST_REQUEST";
export const POST_LABTEST_SUCCESS = "POST_LABTEST_SUCCESS";
export const POST_LABTEST_FAILURE = "POST_LABTEST_FAILURE";
export const POST_LABTEST_RESET = "POST_LABTEST_RESET";

export const EDIT_LABTEST_REQUEST = "EDIT_LABTEST_REQUEST";
export const EDIT_LABTEST_SUCCESS = "EDIT_LABTEST_SUCCESS";
export const EDIT_LABTEST_FAILURE = "EDIT_LABTEST_FAILURE";
export const EDIT_LABTEST_RESET = "EDIT_LABTEST_RESET";

export const DELETE_LABTEST_REQUEST = "DELETE_LABTEST_REQUEST";
export const DELETE_LABTEST_SUCCESS = "DELETE_LABTEST_SUCCESS";
export const DELETE_LABTEST_FAILURE = "DELETE_LABTEST_FAILURE";
export const DELETE_LABTEST_RESET = "DELETE_LABTEST_RESET";

export const GET_PRETEST_REQUEST = "GET_PRETEST_REQUEST";
export const GET_PRETEST_SUCCESS = "GET_PRETEST_SUCCESS";
export const GET_PRETEST_FAILURE = "GET_PRETEST_FAILURE";

export const GET_LABPROFILE_REQUEST = "GET_LABPROFILE_REQUEST";
export const GET_LABPROFILE_SUCCESS = "GET_LABPROFILE_SUCCESS";
export const GET_LABPROFILE_FAILURE = "GET_LABPROFILE_FAILURE";

export const EDIT_LABPROFILE_REQUEST = "EDIT_LABPROFILE_REQUEST";
export const EDIT_LABPROFILE_SUCCESS = "EDIT_LABPROFILE_SUCCESS";
export const EDIT_LABPROFILE_FAILURE = "EDIT_LABPROFILE_FAILURE";
export const EDIT_LABPROFILE_RESET = "EDIT_LABPROFILE_RESET";

export const EDIT_PROFILEOVERVIEW_REQUEST = "EDIT_PROFILEOVERVIEW_REQUEST";
export const EDIT_PROFILEOVERVIEW_SUCCESS = "EDIT_PROFILEOVERVIEW_SUCCESS";
export const EDIT_PROFILEOVERVIEW_FAILURE = "EDIT_PROFILEOVERVIEW_FAILURE";
export const EDIT_PROFILEOVERVIEW_RESET = "EDIT_PROFILEOVERVIEW_RESET";

export const UPLOAD_PROFILE_REQUEST = "UPLOAD_PROFILE_REQUEST";
export const UPLOAD_PROFILE_SUCCESS = "UPLOAD_PROFILE_SUCCESS";
export const UPLOAD_PROFILE_FAILURE = "UPLOAD_PROFILE_FAILURE";
export const UPLOAD_PROFILE_RESET = "UPLOAD_PROFILE_RESET";

export const UPLOAD_IMAGES_REQUEST = "UPLOAD_IMAGES_REQUEST";
export const UPLOAD_IMAGES_SUCCESS = "UPLOAD_IMAGES_SUCCESS";
export const UPLOAD_IMAGES_FAILURE = "UPLOAD_IMAGES_FAILURE";
export const UPLOAD_IMAGES_RESET = "UPLOAD_IMAGES_RESET";

export const GET_LABMEMBER_REQUEST = "GET_LABMEMBER_REQUEST";
export const GET_LABMEMBER_SUCCESS = "GET_LABMEMBER_SUCCESS";
export const GET_LABMEMBER_FAILURE = "GET_LABMEMBER_FAILURE";

export const SINGLE_LABMEMBER_REQUEST = "SINGLE_LABMEMBER_REQUEST";
export const SINGLE_LABMEMBER_SUCCESS = "SINGLE_LABMEMBER_SUCCESS";
export const SINGLE_LABMEMBER_FAILURE = "SINGLE_LABMEMBER_FAILURE";

export const POST_LABMEMBER_REQUEST = "POST_LABMEMBER_REQUEST";
export const POST_LABMEMBER_SUCCESS = "POST_LABMEMBER_SUCCESS";
export const POST_LABMEMBER_FAILURE = "POST_LABMEMBER_FAILURE";
export const POST_LABMEMBER_RESET = "POST_LABMEMBER_RESET";

export const EDIT_LABMEMBER_REQUEST = "EDIT_LABMEMBER_REQUEST";
export const EDIT_LABMEMBER_SUCCESS = "EDIT_LABMEMBER_SUCCESS";
export const EDIT_LABMEMBER_FAILURE = "EDIT_LABMEMBER_FAILURE";
export const EDIT_LABMEMBER_RESET = "EDIT_LABMEMBER_RESET";

export const DELETE_LABMEMBER_REQUEST = "DELETE_LABMEMBER_REQUEST";
export const DELETE_LABMEMBER_SUCCESS = "DELETE_LABMEMBER_SUCCESS";
export const DELETE_LABMEMBER_FAILURE = "DELETE_LABMEMBER_FAILURE";
export const DELETE_LABMEMBER_RESET = "DELETE_LABMEMBER_RESET";

export const GET_QUALIFICATIONS_REQUEST = "GET_QUALIFICATIONS_REQUEST";
export const GET_QUALIFICATIONS_SUCCESS = "GET_QUALIFICATIONS_SUCCESS";
export const GET_QUALIFICATIONS_FAILURE = "GET_QUALIFICATIONS_FAILURE";

export const NEW_TEST_REQUEST = "NEW_TEST_REQUEST";
export const NEW_TEST_SUCCESS = "NEW_TEST_SUCCESS";
export const NEW_TEST_FAILURE = "NEW_TEST_FAILURE";

export const NEW_TEST_DETAIL_REQUEST = "NEW_TEST_DETAIL_REQUEST";
export const NEW_TEST_DETAIL_SUCCESS = "NEW_TEST_DETAIL_SUCCESS";
export const NEW_TEST_DETAIL_FAILURE = "NEW_TEST_DETAIL_FAILURE";
export const NEW_TEST_DETAIL_RESET = "NEW_TEST_DETAIL_RESET";

export const NEW_TEST_APPROVE_REQUEST = "NEW_TEST_APPROVE_REQUEST";
export const NEW_TEST_APPROVE_SUCCESS = "NEW_TEST_APPROVE_SUCCESS";
export const NEW_TEST_APPROVE_FAILURE = "NEW_TEST_APPROVE_FAILURE";
export const NEW_TEST_APPROVE_RESET = "NEW_TEST_APPROVE_RESET";

export const NEW_TEST_DECLINE_REQUEST = "NEW_TEST_DECLINE_REQUEST";
export const NEW_TEST_DECLINE_SUCCESS = "NEW_TEST_DECLINE_SUCCESS";
export const NEW_TEST_DECLINE_FAILURE = "NEW_TEST_DECLINE_FAILURE";
export const NEW_TEST_DECLINE_RESET = "NEW_TEST_DECLINE_RESET";

export const RUNNING_TEST_REQUEST = "RUNNING_TEST_REQUEST";
export const RUNNING_TEST_SUCCESS = "RUNNING_TEST_SUCCESS";
export const RUNNING_TEST_FAILURE = "RUNNING_TEST_FAILURE";

export const RUNNING_TEST_DETAIL_REQUEST = "RUNNING_TEST_DETAIL_REQUEST";
export const RUNNING_TEST_DETAIL_SUCCESS = "RUNNING_TEST_DETAIL_SUCCESS";
export const RUNNING_TEST_DETAIL_FAILURE = "RUNNING_TEST_DETAIL_FAILURE";

export const COMPLETED_TEST_REQUEST = "COMPLETED_TEST_REQUEST";
export const COMPLETED_TEST_SUCCESS = "COMPLETED_TEST_SUCCESS";
export const COMPLETED_TEST_FAILURE = "COMPLETED_TEST_FAILURE";

export const SAMPLES_REQUEST = "SAMPLES_REQUEST";
export const SAMPLES_SUCCESS = "SAMPLES_SUCCESS";
export const SAMPLES_FAILURE = "SAMPLES_FAILURE";

export const ASSIGN_COLLECTOR_REQUEST = "ASSIGN_COLLECTOR_REQUEST";
export const ASSIGN_COLLECTOR_SUCCESS = "ASSIGN_COLLECTOR_SUCCESS";
export const ASSIGN_COLLECTOR_FAILURE = "ASSIGN_COLLECTOR_FAILURE";
export const ASSIGN_COLLECTOR_RESET = "ASSIGN_COLLECTOR_RESET";

export const GET_CONFIRM_REQUEST = "GET_CONFIRM_REQUEST";
export const GET_CONFIRM_SUCCESS = "GET_CONFIRM_SUCCESS";
export const GET_CONFIRM_FAILURE = "GET_CONFIRM_FAILURE";

export const CONFIRM_REQUEST = "CONFIRM_REQUEST";
export const CONFIRM_SUCCESS = "CONFIRM_SUCCESS";
export const CONFIRM_FAILURE = "CONFIRM_FAILURE";
export const CONFIRM_RESET = "CONFIRM_RESET";

export const UPLOAD_REPORT_REQUEST = "UPLOAD_REPORT_REQUEST";
export const UPLOAD_REPORT_SUCCESS = "UPLOAD_REPORT_SUCCESS";
export const UPLOAD_REPORT_FAILURE = "UPLOAD_REPORT_FAILURE";
export const UPLOAD_REPORT_RESET = "UPLOAD_REPORT_RESET";

export const ADD_TEST_REQUEST_REQUEST = "ADD_TEST_REQUEST_REQUEST";
export const ADD_TEST_REQUEST_SUCCESS = "ADD_TEST_REQUEST_SUCCESS";
export const ADD_TEST_REQUEST_FAILURE = "ADD_TEST_REQUEST_FAILURE";
export const ADD_TEST_REQUEST_RESET = "ADD_TEST_REQUEST_RESET";

export const GALLERY_IMAGES_REQUEST = "GALLERY_IMAGES_REQUEST";
export const GALLERY_IMAGES_SUCCESS = "GALLERY_IMAGES_SUCCESS";
export const GALLERY_IMAGES_FAILURE = "GALLERY_IMAGES_FAILURE";

export const UPLOAD_GALLERY_REQUEST = "UPLOAD_GALLERY_REQUEST";
export const UPLOAD_GALLERY_SUCCESS = "UPLOAD_GALLERY_SUCCESS";
export const UPLOAD_GALLERY_FAILURE = "UPLOAD_GALLERY_FAILURE";
export const UPLOAD_GALLERY_RESET = "UPLOAD_GALLERY_RESET";

export const DELETE_GALLERY_REQUEST = "DELETE_GALLERY_REQUEST";
export const DELETE_GALLERY_SUCCESS = "DELETE_GALLERY_SUCCESS";
export const DELETE_GALLERY_FAILURE = "DELETE_GALLERY_FAILURE";
export const DELETE_GALLERY_RESET = "DELETE_GALLERY_RESET";
