export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const EDIT_PROFILE_REQUEST = "EDIT_PROFILE_REQUEST";
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS";
export const EDIT_PROFILE_FAILURE = "EDIT_PROFILE_FAILURE";
export const EDIT_PROFILE_RESET = "EDIT_PROFILE_RESET";

export const GET_TEST_REQUEST = "GET_TEST_REQUEST";
export const GET_TEST_SUCCESS = "GET_TEST_SUCCESS";
export const GET_TEST_FAILURE = "GET_TEST_FAILURE";

export const SINGLE_TEST_REQUEST = "SINGLE_TEST_REQUEST";
export const SINGLE_TEST_SUCCESS = "SINGLE_TEST_SUCCESS";
export const SINGLE_TEST_FAILURE = "SINGLE_TEST_FAILURE";

export const GET_LABLIST_REQUEST = "GET_LABLIST_REQUEST";
export const GET_LABLIST_SUCCESS = "GET_LABLIST_SUCCESS";
export const GET_LABLIST_FAILURE = "GET_LABLIST_FAILURE";

export const GET_LABSERVICE_REQUEST = "GET_LABSERVICE_REQUEST";
export const GET_LABSERVICE_SUCCESS = "GET_LABSERVICE_SUCCESS";
export const GET_LABSERVICE_FAILURE = "GET_LABSERVICE_FAILURE";

export const SINGLE_LABSERVICE_REQUEST = "SINGLE_LABSERVICE_REQUEST";
export const SINGLE_LABSERVICE_SUCCESS = "SINGLE_LABSERVICE_SUCCESS";
export const SINGLE_LABSERVICE_FAILURE = "SINGLE_LABSERVICE_FAILURE";

export const LABTESTBY_CATEGORY_REQUEST = "LABTESTBY_CATEGORY_REQUEST";
export const LABTESTBY_CATEGORY_SUCCESS = "LABTESTBY_CATEGORY_SUCCESS";
export const LABTESTBY_CATEGORY_FAILURE = "LABTESTBY_CATEGORY_FAILURE";

export const GET_LABTEST_REQUEST = "GET_LABTEST_REQUEST";
export const GET_LABTEST_SUCCESS = "GET_LABTEST_SUCCESS";
export const GET_LABTEST_FAILURE = "GET_LABTEST_FAILURE";

export const GET_LABPACKAGE_REQUEST = "GET_LABPACKAGE_REQUEST";
export const GET_LABPACKAGE_SUCCESS = "GET_LABPACKAGE_SUCCESS";
export const GET_LABPACKAGE_FAILURE = "GET_LABPACKAGE_FAILURE";

export const POST_PAYMENTSERVICE_REQUEST = "POST_PAYMENTSERVICE_REQUEST";
export const POST_PAYMENTSERVICE_SUCCESS = "POST_PAYMENTSERVICE_SUCCESS";
export const POST_PAYMENTSERVICE_FAILURE = "POST_PAYMENTSERVICE_FAILURE";
export const POST_PAYMENTSERVICE_RESET = "POST_PAYMENTSERVICE_RESET";

export const POST_CART_REQUEST = "POST_CART_REQUEST";
export const POST_CART_SUCCESS = "POST_CART_SUCCESS";
export const POST_CART_FAILURE = "POST_CART_FAILURE";
export const POST_CART_RESET = "POST_CART_RESET";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_FAILURE";
export const GET_CART_FAILURE = "GET_CART_FAILURE";

export const REMOVE_CART_REQUEST = "REMOVE_CART_REQUEST";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const REMOVE_CART_FAILURE = "REMOVE_CART_FAILURE";
export const REMOVE_CART_RESET = "REMOVE_CART_RESET";

export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_SUCCESS = "PAYMENT_FAILURE";
export const PAYMENT_FAILURE = "PAYMENT_FAILURE";
export const PAYMENT_RESET = "PAYMENT_RESET";

export const CHANGE_PASS_REQUEST = "CHANGE_PASS_REQUEST";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_FAILURE = "CHANGE_PASS_FAILURE";
export const CHANGE_PASS_RESET = "CHANGE_PASS_RESET";

export const FORGET_PASS_REQUEST = "FORGET_PASS_REQUEST";
export const FORGET_PASS_SUCCESS = "FORGET_PASS_SUCCESS";
export const FORGET_PASS_FAILURE = "FORGET_PASS_FAILURE";
export const FORGET_PASS_RESET = "FORGET_PASS_RESET";